using UnityEngine;
using System.Collections;

namespace Assets.Scripts.Common
{

	public enum GAME_EVT
	{
		// game common event
		GAME_START = 0,

		// animator
		ANIMATOR_STATE_ENTER_EXIT,
		ANIMATOR_RUN_STATE_ENTER_EXIT, 

		// Logic
		//切换到站着的状态//
		PLAYER_CHANGE_STATE_EVENT,
		PLAYER_TOUCH_SCENE_OBJECT,
		PLAYER_CLICK_SCENE_OBJECT,
		PLAYER_FREE_MOVE,
		PLAYER_FIRE_READY,
		PLAYER_FIRE_STANDING_FINISH,
		PLAYER_FIRE_EXIT,
		PLAYER_SWITCH_WEAPON,
		SOLDIER_ENTER_LEAVE_DOGER,
		PLAYER_REACHBUNKER,
		
		// ui common event
		WINDOW_SHOW,
		WINDOW_DESTROY,

		// buff event
		BUFF_EVENT,

		// hud event
		HUD_FIRE,
		HUD_CAMERA_MOVE,
		HUD_RELOAD,
		HUD_MOVE,
		HUD_NEED_UPDATE_MOVE_BTN,
		HUD_THROW_GRENADE,
		HUD_SWITCH_WEAPON,
		HUD_USE_SKILL_1,
		HUD_USE_SKILL_2,
		HUD_USE_SKILL_3,
		HUD_SWITCH_WEAPON_FINISH,
		HUD_COUNT_DOWN,

		// 如果新增方法,请在下方LEVEL_EDITOR_EVT中按相同的顺序添加
		LEVEL_START,
		LEVEL_SPAWN_MASTER_PLAYER,
		LEVEL_SPAWN_MONSTER_GRP,
		LEVEL_MONSTER_GRP_KILLED,
		LEVEL_TRIGGER_ENTER,
		LEVEL_TRIGGER_EXIT,
		LEVEL_DRAMA_END,
		LEVEL_MONSTER_DIE,
		LEVEL_END,
		LEVEL_NEAR_DODGE_REACH,
		LEVEL_MASTER_ENTER_DODGE,
		LEVEL_MASTER_LEAVE_DODGE,
		LEVEL_MASTER_FIRST_ENTER_DODGE,
		LEVEL_MONSTER_GRP_ACTIVE,
		//
		MAX,
	}

	public enum LEVEL_EDITOR_EVT
	{
		LEVEL_START = 0,
		LEVEL_SPAWN_MASTER_PLAYER,
		LEVEL_SPAWN_MONSTER_GRP,
		LEVEL_MONSTER_GRP_KILLED,
		LEVEL_TRIGGER_ENTER,
		LEVEL_TRIGGER_EXIT,
		LEVEL_DRAMA_END,
		LEVEL_MONSTER_DIE,
		LEVEL_END,
		LEVEL_NEAR_DODGE_REACH,
		LEVEL_MASTER_ENTER_DODGE,
		LEVEL_MASTER_LEAVE_DODGE,
		LEVEL_MASTER_FIRST_ENTER_DODGE,
		LEVEL_MONSTER_GRP_ACTIVE,
	}

}